export const ComponentsDrinks = [
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/f04/couhbzjruz336fg1ri6i5woked8m8yal_thumb_256x256.jpg',
        nameDrinks: 'Грушевый милкшейк',
        descriptionDrinks: 'Молочный коктейль с сочной грушей и соленой карамелью',
        priceDrinks:'380р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/379/37956d9ef0857c0a950eaaa60665b923_thumb_256x256.png',
        nameDrinks: 'Джонни-единорог',
        descriptionDrinks: 'Фирменный милкшейк с пломбиром, мандариновым соком, сиропом бабл гам и яркой шапкой. Все, что вы так любили в детстве, в одном коктейле!',
        priceDrinks:'330р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/6c1/6c1ba79cefb3b239321b04978783183d_thumb_256x256.png',
        nameDrinks: 'Джинни Единорожка',
        descriptionDrinks: 'Говорят, у каждого единорога должна быть подруга. Встречайте! Молочный коктейль на основе ананасового сока, пломбира, клубники и сиропа бабл-гам.',
        priceDrinks:'320р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/fd3/fd3dcd154ccf941b2641e4d8ee3fa89f_thumb_256x256.png',
        nameDrinks: 'Милкшейк мятное яблоко',
        descriptionDrinks: 'Милкшейк из ванильного мороженого, яблочного сока и взбитых сливок с мятно-яблочным вкусом.',
        priceDrinks:'320р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/6d5/og548sgts8wfu4o0gljt1tqz2g7fdaj5_thumb_256x256.png',
        nameDrinks: 'Милкшейк ягодный',
        descriptionDrinks: 'Милкшейк на основе ванильного мороженого с добавлением черники и вишни.',
        priceDrinks:'330р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/bb5/bb562347fb6882e441a2d0f06a37f0b0_thumb_256x256.png',
        nameDrinks: 'Ванильный милкшейк',
        descriptionDrinks: 'Изящное сочетание сливочного мороженого, молока и нежной сладости ванильного сиропа.',
        priceDrinks:'270р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/849/849eaa80e92963b9d5f076c025223046_thumb_256x256.png',
        nameDrinks: 'Клубничный милкшейк',
        descriptionDrinks: 'Легендарный молочный коктейль с мороженым и сладким, как свежая клубника, сиропом.',
        priceDrinks:'280р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/9ec/6dzh73bvv2yrmascp78kzp5pzf47vcqv_thumb_256x256.png',
        nameDrinks: 'Смузи банан-клубника',
        descriptionDrinks: 'Смузи на основе персикового сока с бананом и клубникой.',
        priceDrinks:'280р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/e7e/e7ed61f33f7cdcecc6ccb173290d4084_thumb_256x256.png',
        nameDrinks: 'Морс клюквенный',
        descriptionDrinks: 'Яркий, освежающий и очень полезный домашний морс из клюквы.',
        priceDrinks:'140р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/9d2/9d28112917b763a2250f54b0d1631635_thumb_256x256.png',
        nameDrinks: 'Морс клюквенный 1 л',
        descriptionDrinks: 'Домашний витаминный морс из ягод клюквы в большом объёме.',
        priceDrinks:'240р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/3a7/3a7273b82d87fac24174c292b573f357_thumb_256x256.png',
        nameDrinks: 'Лимонад Маракуйя',
        descriptionDrinks: 'Освежающий коктейль из содовой, цитрусов и мяты с добавлением пюре маракуйя.',
        priceDrinks:'170р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/9cd/9cd51015ceeb5576863bdde2a9f29759_thumb_256x256.png',
        nameDrinks: 'Лимонад Маракуйя 1 л',
        descriptionDrinks: 'Освежающий коктейль из содовой, цитрусов и мяты с добавлением пюре маракуйя в большом объёме.',
        priceDrinks:'300р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/3d5/3d587ab884bf90c6666aa5fb9e14e820_thumb_256x256.png',
        nameDrinks: 'Лимонад классический',
        descriptionDrinks: 'Бодрит и утоляет жажду – классика!',
        priceDrinks:'160р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/b1c/b1c0ed4f47d5b8ec7bb46e777a902ec4_thumb_256x256.png',
        nameDrinks: 'Лимонад классический 1л',
        descriptionDrinks: 'Классический лимонад теперь и в большом объеме. Бодрит и утоляет жажду – классика.',
        priceDrinks:'200р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/ff6/7tz5fgdixt7lhokubr2638tyne27iwcs_thumb_256x256.png',
        nameDrinks: 'Мандариновый пунш',
        descriptionDrinks: 'Мандариновый пунш с тимьяном. Рекомендуем разогреть и пить горячим',
        priceDrinks:'240р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/5dd/nnra8drmuzoz8c7zstix5mvg5ncczrjq_thumb_256x256.png',
        nameDrinks: 'Коктейль клюква-вишня',
        descriptionDrinks: 'Клюквенный коктейль с тимьяном, вишней и корицей. Рекомендуем разогреть и пить горячим.',
        priceDrinks:'240р.',
    },
    {
        imageDrinks: 'https://izhevsk.mama-pizza.ru/upload/iblock/49e/1hom8ougy1x3dcpupqp1l9iw9f6abahm_thumb_256x256.png',
        nameDrinks: 'Милкшейк Дино',
        descriptionDrinks: 'Молочный коктейль со вкусом маракуйя и мятным топпингом',
        priceDrinks:'350р.',
    },
]