export const ComponentsPizzaclassic = [
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/9c8/c7xzyzu33q5l4ec316qnc26t0arjpkcp_thumb_256x256.png',
        nameclassic: 'Пицца сливочная с ветчиной и томатами',
        descriptionclassic: 'Нежнейшая пицца с ветчиной, томатами, прованскими травами и сыром моцарелла. В основе — сливочный соус с маскарпоне. Диаметр пиццы — 30 см.',
        priceclassic:'470р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/38c/fn0p3rfzgl0pq9tpuune10y7pwt1p81p_thumb_256x256.png',
        nameclassic: 'Пицца с запеченной индейкой и говядиной',
        descriptionclassic: 'Буженина из индейки и говядина под сырами моцарелла и гауда, покрытые свежей рукколой, на классическом тесте. В основе — пряный томатный соус. Диаметр пиццы — 30 см.',
        priceclassic:'570р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/e34/6ubxqavcnke9oqxybphoo8xcddhj8qb0_thumb_256x256.png',
        nameclassic: 'Пицца с колбасками гриль и соусом барбекю',
        descriptionclassic: 'Колбаски гриль, пряные огурцы, красный лук, сыр моцарелла в сочетании с ароматными соусами: сырный и барбекю Диаметр пиццы — 30 см.',
        priceclassic:'510р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/56c/56c45b99177da042e60f3dd5f30c2cea_thumb_256x256.png',
        nameclassic: 'Четыре сыра',
        descriptionclassic: 'Неустаревающая классика сочетания сыров: сыр дорблю, чеддер, моцарелла, гауда и сливочный соус с маскарпоне. Диаметр пиццы — 30 см.',
        priceclassic:'500р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/829/829f80abd4898d1bbfd7e208c82223fa_thumb_256x256.png',
        nameclassic: 'Альфредо',
        descriptionclassic: 'Сочная курица, шампиньоны, свежие томаты, моцарелла и сливочный соус альфредо со шпинатом - объединились, чтобы Вам точно понравилась эта новинка! Диаметр пиццы — 30 см. *В состав соуса входит чеснок.',
        priceclassic:'490р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/c83/c83f003e258546c2760063fb9fdd8ed2_thumb_256x256.png',
        nameclassic: 'Жульен с индейкой',
        descriptionclassic: 'Филе индейки, сыр моцарелла и шампиньоны в сочетании с нежным сливочным соусом. Диаметр пиццы — 30 см.',
        priceclassic:'470р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/bc6/bc6c99b2908f4a68d8103afe3826db1a_thumb_256x256.png',
        nameclassic: 'Карбонара',
        descriptionclassic: 'Ветчина, бекон, свежие томаты, сыр моцарелла в сочетании со сливочно-чесночным соусом в нежной омлетной заливке. Диаметр пиццы — 30 см.',
        priceclassic:'490р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/10f/10f751c5c61f58f473b5fe2d55f6e67c_thumb_256x256.png',
        nameclassic: 'Белиссимо',
        descriptionclassic: 'Так просто и так вкусно, что Белиссимо! В составе пиццы: колбаски охотничьи, бекон, ветчина, помидоры, болгарский перец, сыр моцарелла, пряный томатный соус. Диаметр пиццы — 30 см.',
        priceclassic:'470р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/565/565a2b6ab2cb2b727a55bc68828c7a9a_thumb_256x256.png',
        nameclassic: 'С ветчиной и сыром',
        descriptionclassic: 'Мы нашли способ, как из минимума ингредиентов получить максимум вкуса: моцарелла, ветчина, охотничьи колбаски и томатный соус очень талантливы! Диаметр пиццы — 30 см.',
        priceclassic:'470р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/e16/e16618cff7d87ebdde13e5e51d646273_thumb_256x256.png',
        nameclassic: 'С курицей, ананасами и беконом',
        descriptionclassic: 'Яркая пицца с запоминающимся сладким вкусом! Сочное куриное филе, ароматный бекон и сладкие ананасы с нежным сыром моцарелла на пряном томатном соусе. Диаметр пиццы — 30 см.',
        priceclassic:'490р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/199/1996317287bc4b8b2828add30e676302_thumb_256x256.png',
        nameclassic: 'Мама Пицца',
        descriptionclassic: 'Фирменная пицца, с которой вы точно подружитесь! В её составе ветчина, говядина, мясной рулет, помидоры, болгарский перец, соленые огурцы, сыр моцарелла. В основе — томатно-пряный соус. Диаметр пиццы — 30 см.',
        priceclassic:'520р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/e25/e25f02010763efe0d34892d0cbf5087c_thumb_256x256.png',
        nameclassic: 'Супермясная 2.0',
        descriptionclassic: 'Сытная пицца с сыром моцарелла, томатно-пряным соусом  и огромным количеством мяса: сочная курица, копченая говядина, сервелат, пряные колбаски пепперони, мясной рулет и орегано. Диаметр пиццы — 30 см.',
        priceclassic:'570р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/f03/f03d561dab113c26dc01c0d36307780a_thumb_256x256.png',
        nameclassic: 'Колбасная',
        descriptionclassic: 'Не пицца, а песня! В ней сливаются ветчина, сервелат, маринованные огурцы, болгарский перец, томатный пряный соус и сразу три вида сыра: чеддер, гауда и моцарелла. Диаметр пиццы — 30 см.',
        priceclassic:'480р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/84a/84a1e44aa8972d2b393ca5dc90707899_thumb_256x256.png',
        nameclassic: 'С ветчиной и грибами  ',
        descriptionclassic: 'Мы любим осень, грибы и запах леса. Эту любовь мы передали пицце, в составе которой маринованные шампиньоны, ветчина, помидоры, моцарелла. В основе — ароматный грибной соус. Диаметр пиццы — 30 см.',
        priceclassic:'470р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/bcf/bcfd78208048f6a5fe1b2bdc0d1cc3e4_thumb_256x256.png',
        nameclassic: 'Пепперони',
        descriptionclassic: 'Элегантная итальянская классика, в которой звучит пикантная колбаска пепперони, моцарелла и пряный томатный соус. Диаметр пиццы — 30 см. *Присутствует умеренная острота от колбасы пепперони',
        priceclassic:'480р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/176/176944490a45c98ed80a32f41093b064_thumb_256x256.png',
        nameclassic: 'Барбекю',
        descriptionclassic: 'Мы готовим эту пиццу и вспоминаем лето. В ней объединились говядина михайловская, бекон, моцарелла, красный лук и два ароматных соуса: томатный и барбекю. Диаметр пиццы — 30 см.',
        priceclassic:'490р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/ec1/ec1ba151ffe87ccb1d87822b3af65bcc_thumb_256x256.png',
        nameclassic: 'Чесночный цыпленок',
        descriptionclassic: 'Сытная, сочная, ароматная – такой мы создавали эту пиццу! В составе: куриное филе, бекон, томаты, сыр моцарелла. В основе — чесночный соус. Диаметр пиццы — 30 см.',
        priceclassic:'470р.',
    },
    {
        imageclassic: 'https://izhevsk.mama-pizza.ru/upload/iblock/ce8/ce8460f5230bc49041619259f5bcddc8_thumb_256x256.png',
        nameclassic: 'Маргарита',
        descriptionclassic: 'Мы обновили нашу пиццу и сделали ее более классической: свежие томаты, фирменный пряный томатный соус, моцарелла, базилик и орегано. Диаметр пиццы — 30 см.',
        priceclassic:'430р.',
    },
]